//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
namespace ClassDiagram
{
	using System;
	using System.Collections.Generic;
	using System.Linq;
	using System.Text;

	/// <remarks>
	/// Animal
	/// Instances:0, 
	/// MethodCalls:0, 
	/// Average Associations:0
	/// </remarks>
	public class Animal
	{
		public virtual object Name
		{
			get;
			set;
		}

		public virtual object Age
		{
			get;
			set;
		}

		public virtual void MakeNoice()
		{
            Console.WriteLine("Wau Wau");
		}

        ~Animal()
        { }

	}
}

