//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
namespace ClassDiagram
{
	using System;
	using System.Collections.Generic;
	using System.Linq;
	using System.Text;

	public class Cat : Animal
	{
		public virtual object Breed
		{
			get;
			set;
		}

		public virtual void ToMiaow()
		{
			throw new System.NotImplementedException();
		}

	}
}

