//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
namespace ClassDiagram
{
	using System;
	using System.Collections.Generic;
	using System.Linq;
	using System.Text;

	public class Person
	{
		public virtual object Name
		{
			get;
			set;
		}

		public virtual object Age
		{
			get;
			set;
		}

		public virtual Animal Animal
		{
			get;
			set;
		}

		public virtual void PlayWithAnimal()
		{
            Console.WriteLine("Play animal");
            this.Animal.MakeNoice();
		}

		public virtual void BuyDog()
		{
            this.Animal = new Animal();
		}

	}
}

