package com.grill.customerserviceclient.helper;

/**
 * Created by Flo on 15.12.2014.
 */
public enum StateMsgs {

    GENERAL_ERROR,
    CONNECTION_ERROR,

    REST_ADD_CUSTOMER_RESULT,
    REST_DELETE_CUSTOMER_RESULT,
    REST_RESPONSE_CUSTOMER_LIST,
    REST_RESPONSE_ORDER_LIST,
    REST_RESPONSE_ADD_ORDER,
    REST_DELETE_ORDER_RESULT,
    REST_GET_RESPONSE_ERROR,


    SOAP_ADD_CUSTOMER_RESULT,
    SOAP_DELETE_CUSTOMER_RESULT,
    SOAP_RESPONSE_CUSTOMER_LIST,
    SOAP_RESPONSE_ORDER_LIST,
    SOAP_RESPONSE_ADD_ORDER,
    SOAP_DELETE_ORDER_RESULT,
    SOAP_GET_RESPONSE_ERROR,
    SOAP_XML_PARSE_ERROR,
}
